minvws/nl-covid19-notification-app-website

README.i18n.md
_config.yml
_data/languages.yml
_data/translations.yml
_features/001-demo-with-video-en.md
_features/002-in-progress-no-text-en.md
_features/003-in-progress-dummy-en.md
_features/004-in-progress-no-text-en.md
_features/004-in-progress-no-text.md
_includes/footer.html
_includes/head.html
_includes/header.html
_layouts/default.html
en/index.md

patch for issue #4

---

README.md

Changed project name in README.md to reflect new repository name

patch issue#14 new repository name

---

404.md

patch for issue #10 - 404 pagina

patch for issue #10 - 404 pagina

---

_data/translations.yml

Patch for multiple translation (en) errors.

patch for multiple translation (en) errors

---

README.md

patch for issue #33 - link to README.i18n.md

patch for issue #33 - link to README.i18n.md

---

README.md

Update Readme.md honorable mentions and gratitude - add Joost Soeterbroek

Update Readme.md honorable mentions and gratitude

---

README.md

A quick grasp of sentiment of the general public as input for the App website

Results of survey - insights views genral public

---

404.md
_layouts/minimal.html

patch for issue #40 - minimal layout 404 page

patch for issue #40 - minimal layout 404 page

---

_config.yml

update _config.yml reponaam

---

.gitignore
.travis.yml
Gemfile
README.md
_config.yml
script/cibuild

#73 patch for CI testing with Travis.

#73 patch for CI testing with Travis 

---

_data/translations.yml

PR to complete the english translation for `feedback-answer-submitted-yes_md`.

Small translation improvement for feedback answer submitted yes

---

pages/accessibility-in-app/accessibility-in-app-bg.md
pages/accessibility-in-app/accessibility-in-app-es.md
pages/accessibility-in-app/accessibility-in-app-fr.md
pages/accessibility-in-app/accessibility-in-app-pl.md
pages/accessibility-in-app/accessibility-in-app-ro.md
pages/accessibility-in-app/accessibility-in-app-tr.md
pages/colofon-in-app/colofon-in-app-bg.md
pages/colofon-in-app/colofon-in-app-es.md
pages/colofon-in-app/colofon-in-app-fr.md
pages/colofon-in-app/colofon-in-app-pl.md
pages/colofon-in-app/colofon-in-app-ro.md
pages/colofon-in-app/colofon-in-app-tr.md
pages/privacy-in-app/privacy-in-app-bg.md
pages/privacy-in-app/privacy-in-app-es.md
pages/privacy-in-app/privacy-in-app-fr.md
pages/privacy-in-app/privacy-in-app-pl.md
pages/privacy-in-app/privacy-in-app-ro.md
pages/privacy-in-app/privacy-in-app-tr.md
pages/test-en-onderzoeksversie-in-app/test-en-onderzoeksversie-in-app-bg.md
pages/test-en-onderzoeksversie-in-app/test-en-onderzoeksversie-in-app-es.md
pages/test-en-onderzoeksversie-in-app/test-en-onderzoeksversie-in-app-fr.md
pages/test-en-onderzoeksversie-in-app/test-en-onderzoeksversie-in-app-pl.md
pages/test-en-onderzoeksversie-in-app/test-en-onderzoeksversie-in-app-ro.md
pages/test-en-onderzoeksversie-in-app/test-en-onderzoeksversie-in-app-tr.md

Signed-off-by: mikecodo <mike@smoothworks.nl>

added bg, es, fr, pl  ro, tr pages

---

pages/accessibility-in-app/accessibility-in-app-ar.md
pages/accessibility-in-app/accessibility-in-app-bg.md
pages/accessibility-in-app/accessibility-in-app-de.md
pages/accessibility-in-app/accessibility-in-app-en.md
pages/accessibility-in-app/accessibility-in-app-es.md
pages/accessibility-in-app/accessibility-in-app-fr.md
pages/accessibility-in-app/accessibility-in-app-nl.md
pages/accessibility-in-app/accessibility-in-app-pl.md
pages/accessibility-in-app/accessibility-in-app-ro.md
pages/accessibility-in-app/accessibility-in-app-tr.md
pages/colofon-in-app/colofon-in-app-ar.md
pages/colofon-in-app/colofon-in-app-bg.md
pages/colofon-in-app/colofon-in-app-de.md
pages/colofon-in-app/colofon-in-app-en.md
pages/colofon-in-app/colofon-in-app-es.md
pages/colofon-in-app/colofon-in-app-fr.md
pages/colofon-in-app/colofon-in-app-nl.md
pages/colofon-in-app/colofon-in-app-pl.md
pages/colofon-in-app/colofon-in-app-ro.md
pages/colofon-in-app/colofon-in-app-tr.md

Signed-off-by: mikecodo <mike@smoothworks.nl>

removed H2 text

---

ar/pers.md
bg/pers.md
de/pers.md
en/pers.md
es/pers.md
fr/pers.md
nl/pers.md
pers.md
pl/pers.md
ro/pers.md
tr/pers.md

Add pers.md pages

---

_includes/privacy-text-en.md
_includes/privacy-text.md
ar/privacy-in-app.md
ar/privacy.md
bg/privacy-in-app.md
bg/privacy.md
de/privacy-in-app.md
de/privacy.md
en/privacy-in-app.md
en/privacy.md
es/privacy-in-app.md
es/privacy.md
fr/privacy-in-app.md
fr/privacy.md
pl/privacy-in-app.md
pl/privacy.md
ro/privacy-in-app.md
ro/privacy.md
tr/privacy-in-app.md
tr/privacy.md

Update the Dutch privacy statement.
Add the English privacy statement and link to it from all other
languages.

Update privacy statements

---

_data/languages.yml

This was dummy content by the looks of it.

Remove non-existing languages

---

_data/translations.yml

Signed-off-by: Mike Leander <mike@smoothworks.nl>

friday -> Friday

---

_includes/header.html

Only show a subtitle (load h2 element in header) when content for it is available

---

css/_language-picker.scss

Might be a fix for issue #258 ! (Works locally, not sure if this causes other issues)

#258 remove links from tab route when menu is closed

---

_includes/head.html

Sluit #32 gedeeltelijk.
PR #114 gesloten omdat deze orphaned was geworden.

SEO: Voeg hreflang locatizatie tags toe aan header

---

nl/privacy.md

Same fix as https://github.com/minvws/nl-covid19-notification-app-website/pull/274

Update Privacy.md -- Fix typo HeHet

---

css/_faq.scss
css/_footer.scss
css/_statements.scss
css/content-block.scss
css/main.scss

Some classes were still using static hex values, instead of the already made Sass variable. I made sure each color Sass variable is now used, instead of static hex values.

Changes static hex values to Sass variables

---

_data/translations.yml
_includes/footer-js.html
_includes/footer-phone.html

De openingstijden zijn gewijzigd! In het weekend zijn de openingstijden verruimd naar dezelfde tijden als doordeweeks. 
Graag mag deze wijziging meteen door naar acceptatie.

Aangepaste openingstijden

---

_data/translations.yml
_includes/footer-phone.html
css/_footer.scss

Voegt helpdesk e-mailadres toe aan footer

Added e-mail address in footer

---

_questions/nl/6-hoe-werkt-de-app.md

Signed-off-by: Anneke Sinnema <mail@annekesinnema.nl>

Added points (copy change only)

---

_statements/nl/5-mandatory.md

Hoewel er in zoveel worden staat dat je niet verplicht bent de app te gebruiken geeft het antwoord op dit moment geen duidelijk "ja" of "nee" antwoord. 
Door duidelijk "nee" te zeggen is het meteen duidelijk dat je niet verplicht bent om de app te gebruiken.

Direct antwoord op de vraag "is de app verplicht?"

---

_data/translations.yml
ar/accessibility-in-app.md
bg/accessibility-in-app.md
de/accessibility-in-app.md
en/accessibility-in-app.md
es/accessibility-in-app.md
fr/accessibility-in-app.md
nl/accessibility-in-app.md
pl/accessibility-in-app.md
ro/accessibility-in-app.md
tr/accessibility-in-app.md

There were some duplicates of pull-requests in the repo, and to resolve them in one swoop, I created this PR that combines some suggestions.
Thanks go to 
@WilliamDEdwards, @lokerhp and @amvi88 for pointing out the missing translations. 
@DaanAcohen (added a comma in the english accessibility text, see https://github.com/minvws/nl-covid19-notification-app-website/pull/243 )
@sjmclean24 (I think it's a great idea to add mailto subjects - https://github.com/minvws/nl-covid19-notification-app-website/pull/284 )

Combined various feedback on English translations

---

css-rtl/_stories-rtl.scss
css-rtl/header-rtl.scss
css-rtl/main-rtl.scss

Styling fixes... I kept this seperate from translating, this branch just contains styling fixes:
Fixes this:
to this:

Nieuwe homepage: fixes voor arabisch rechts-naar-links

---

_includes/faq.html
_includes/footer.html
_includes/information.html
_layouts/faq-overview.html
nl/colofon.md

Fix HTML issues
